# Copyright (c) 2026 BY-SYSTEMS SRL. MIT License.
# SPDX-License-Identifier: MIT
# Repo: https://github.com/by-openclaw/lib-opnsense
"""OPNsense auth API key manager — create, list, and delete API keys for users.

API keys are NOT standard CRUD entities. On OPNsense 26.1, the endpoints use
inconsistent identifiers (a known rough edge from the MVC migration).

Endpoints:
    create  POST auth/user/add_api_key/{username}    — username string
    search  POST auth/user/search_api_key/{any}      — returns ALL keys (param ignored)
    delete  POST auth/user/del_api_key/{id}          — base64 ID from search results
    apply   None — auth changes apply immediately

Redact fields: key, secret (partial reveal via structlog)
Logging: custom (INFO=create, WARNING=delete, ERROR=failure)
Safety:  see docs/test-zone-plan.md §M04
"""

from __future__ import annotations

import logging
from typing import Any

from opnsense.client import OpnsenseClient
from opnsense.models.base import EnsureResult

logger = logging.getLogger(__name__)


class AuthApiKeyManager:
    """Manage OPNsense API keys for local users.

    API keys are generated by OPNsense (not user-supplied). Each key is
    tied to a user and identified by a base64 ID in the search results.

    Usage::

        async with OpnsenseClient(...) as client:
            mgr = AuthApiKeyManager(client)

            # List all API keys
            keys = await mgr.list_keys()

            # Create a new key (returns key+secret — store immediately!)
            result = await mgr.create_key(username="inttest-bob")

            # Delete a key by its base64 ID
            result = await mgr.delete_key(key_id="base64-id-from-search")
    """

    def __init__(self, client: OpnsenseClient) -> None:
        """Initialise the API key manager.

        Args:
            client: An :class:`OpnsenseClient` instance.
        """
        self._client = client

    async def list_keys(self, username: str | None = None) -> list[dict[str, Any]]:
        """List API keys, optionally filtered by username.

        Note: OPNsense 26.1 returns ALL keys regardless of the endpoint
        parameter. Client-side filtering by username is applied when provided.

        Args:
            username: Optional username to filter results.

        Returns:
            List of key dicts with 'username', 'key', and 'id' fields.
        """
        # The endpoint param is ignored by OPNsense but we pass it anyway
        endpoint = "auth/user/search_api_key/all"
        rows = await self._client.search(endpoint)
        if username:
            return [r for r in rows if r.get("username") == username]
        return rows

    async def create_key(
        self,
        username: str,
        check_mode: bool = False,
    ) -> EnsureResult:
        """Generate a new API key for a user.

        OPNsense generates the key+secret pair. The secret is only returned
        once at creation time — it cannot be retrieved later.

        Args:
            username:   Username string (not UUID or UID).
            check_mode: If True, return what would happen without changes.

        Returns:
            EnsureResult with action='created'. ``after`` contains the
            generated key and secret (store immediately — secret shown once).

        Raises:
            OpnsenseError: If key creation fails (e.g. user doesn't exist).
        """
        if check_mode:
            return EnsureResult(
                changed=True,
                action="created",
                after={
                    "username": username,
                    "key": "<REDACTED:key>",
                    "secret": "<REDACTED:secret>",
                },
            )

        body = await self._client.post(f"auth/user/add_api_key/{username}")

        if body.get("result") not in ("ok", "saved"):
            from opnsense.exceptions import OpnsenseError

            raise OpnsenseError(
                f"Failed to create API key for user '{username}'",
                endpoint=f"auth/user/add_api_key/{username}",
            )

        logger.info(
            "api_key created for user=%s",
            username,
            extra={
                "action": "created",
                "changed": True,
                "username": username,
                "key": "<REDACTED:key>",
                "secret": "<REDACTED:secret>",
            },
        )
        return EnsureResult(
            changed=True,
            action="created",
            after={
                "username": username,
                "key": body.get("key", ""),
                "secret": body.get("secret", ""),
            },
        )

    async def delete_key(
        self,
        key_id: str,
        check_mode: bool = False,
    ) -> EnsureResult:
        """Delete an API key by its base64 ID.

        Args:
            key_id:     Base64 ID from search_api_key results.
            check_mode: If True, return what would happen without changes.

        Returns:
            EnsureResult with action='deleted'.
        """
        if check_mode:
            return EnsureResult(
                changed=True,
                action="deleted",
                before={"key_id": key_id},
            )

        await self._client.post(f"auth/user/del_api_key/{key_id}")

        logger.warning(
            "api_key deleted key_id=%s",
            key_id[:8] + "...",
            extra={"action": "deleted", "changed": True, "key_id": "<REDACTED:key_id>"},
        )
        return EnsureResult(
            changed=True,
            action="deleted",
            before={"key_id": key_id},
        )

    async def delete_all_keys(
        self,
        username: str,
        check_mode: bool = False,
    ) -> EnsureResult:
        """Delete all API keys for a user.

        Args:
            username:   Username to delete keys for.
            check_mode: If True, return what would happen without changes.

        Returns:
            EnsureResult with changed=True if keys were deleted, noop if none exist.
        """
        keys = await self.list_keys(username=username)

        if not keys:
            return EnsureResult(changed=False, action="noop")

        if check_mode:
            return EnsureResult(
                changed=True,
                action="deleted",
                before={"username": username, "key_count": len(keys)},
            )

        for key_row in keys:
            key_id = key_row.get("id", "")
            if key_id:
                await self._client.post(f"auth/user/del_api_key/{key_id}")

        return EnsureResult(
            changed=True,
            action="deleted",
            before={"username": username, "key_count": len(keys)},
        )
