#!/usr/bin/env bash
# =============================================================================
# build-api-schema-audit.sh — Convert probed JSON schemas to .md audit
# =============================================================================
# Copyright (c) BY-SYSTEMS SRL
# SPDX-License-Identifier: MIT
# https://github.com/by-openclaw/lib-opnsense
# =============================================================================
# Reads JSON files from docs/api/data/{version}/ and produces
# docs/api/schema-audit.md — the permanent, diffable .md record.
#
# Called automatically by probe-api-schemas.sh, or standalone:
#   ./build-api-schema-audit.sh [--indir <path>]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_DIR="$(dirname "$SCRIPT_DIR")"
INDIR=""
OUTFILE="${TOOL_DIR}/docs/api/schema-audit.md"

# --- CLI arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --indir) INDIR="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

# Default: follow the "latest" symlink
if [[ -z "$INDIR" ]]; then
  if [[ -L "${TOOL_DIR}/docs/api/data/latest" ]]; then
    INDIR="$(readlink -f "${TOOL_DIR}/docs/api/data/latest")"
  else
    INDIR="${TOOL_DIR}/docs/api/data"
  fi
fi

MANIFEST_FILE="${INDIR}/manifest.jsonl"
VERSION_FILE="${INDIR}/version.json"

if [[ ! -d "$INDIR" ]]; then
  echo "No probe data in $INDIR — run probe-api-schemas.sh first." >&2
  exit 1
fi

# --- Read version metadata ---
OPN_VERSION="unknown"
OPN_PRODUCT="OPNsense"
OPN_ARCH="unknown"
PROBE_TIMESTAMP="unknown"
if [[ -f "$VERSION_FILE" ]]; then
  OPN_VERSION=$(jq -r '.opnsense_version // "unknown"' "$VERSION_FILE")
  OPN_PRODUCT=$(jq -r '.product // "OPNsense"' "$VERSION_FILE")
  OPN_ARCH=$(jq -r '.arch // "unknown"' "$VERSION_FILE")
  PROBE_TIMESTAMP=$(jq -r '.probe_timestamp // "unknown"' "$VERSION_FILE")
fi

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
cat > "$OUTFILE" << 'HEADER'
# OPNsense API Schema Audit

> **Purpose:** Permanent record of every probed API endpoint — fields, enums,
> defaults, types, and HTTP status. Generated by `scripts/probe-api-schemas.sh`
> and `scripts/build-api-schema-audit.sh`.
>
> **This file is the ground-truth for Ansible role development.**
> It captures what the API actually returns, not what the docs say.

HEADER

echo "## Probe Metadata" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "| Property | Value |" >> "$OUTFILE"
echo "|----------|-------|" >> "$OUTFILE"
echo "| **OPNsense Version** | \`${OPN_VERSION}\` |" >> "$OUTFILE"
echo "| **Product** | ${OPN_PRODUCT} (${OPN_ARCH}) |" >> "$OUTFILE"
echo "| **Probe timestamp** | ${PROBE_TIMESTAMP} |" >> "$OUTFILE"
echo "| **Audit generated** | ${TIMESTAMP} |" >> "$OUTFILE"
if [[ -f "$MANIFEST_FILE" ]]; then
  manifest_count=$(wc -l < "$MANIFEST_FILE")
  echo "| **Endpoints probed** | ${manifest_count} |" >> "$OUTFILE"
fi
echo "| **Source JSONs** | \`docs/api/data/${OPN_VERSION//[^a-zA-Z0-9._-]/_}/\` |" >> "$OUTFILE"
echo "" >> "$OUTFILE"

# ---------------------------------------------------------------------------
# Conventions reference (from rest-api-reference.md)
# ---------------------------------------------------------------------------
cat >> "$OUTFILE" << 'CONVENTIONS'
## API Type Conventions

| Type | Read shape | Write shape | Example |
|------|-----------|-------------|---------|
| `string-bool` | `"1"` / `"0"` | `"1"` / `"0"` | `enabled` |
| `int-like string` | `"443"` | `"443"` | `port`, `sequence` |
| `enum dict` | `{"wan":{"value":"WAN","selected":1},...}` | `"wan"` (selected key) | `interface` |
| `string` | `"text"` | `"text"` | `description` |
| `list` | `["uuid1","uuid2"]` | `"uuid1,uuid2"` | `categories` |
| `csv` | `"10.0.0.0/8\n172.16.0.0/12"` | newline-separated | `content` |

> Changes are **staged** until `reconfigure` / `apply` is called.
> Auth: HTTP Basic with `API-key:API-secret`.

---

CONVENTIONS

# ---------------------------------------------------------------------------
# Process each schema JSON
# ---------------------------------------------------------------------------
# Collect unique labels in order
declare -a LABELS_SEEN=()
declare -A LABEL_DONE=()

for f in "$INDIR"/*.json; do
  [[ -f "$f" ]] || continue
  base=$(basename "$f" .json)
  if [[ "$base" == *.request ]]; then
    continue
  fi
  label="${base%%__*}"
  if [[ -z "${LABEL_DONE[$label]:-}" ]]; then
    LABELS_SEEN+=("$label")
    LABEL_DONE[$label]=1
  fi
done

SECTION=0

for label in "${LABELS_SEEN[@]}"; do
  SECTION=$((SECTION + 1))

  echo "## ${SECTION}. ${label}" >> "$OUTFILE"
  echo "" >> "$OUTFILE"

  # Process schema, search, global in that order
  for type in schema search global; do
    jsonfile="${INDIR}/${label}__${type}.json"
    httpfile="${INDIR}/${label}__${type}.http"
    requestfile="${INDIR}/${label}__${type}.request.json"

    [[ -f "$jsonfile" ]] || continue

    http_code="???"
    [[ -f "$httpfile" ]] && http_code=$(<"$httpfile")

    echo "### ${type} — HTTP ${http_code}" >> "$OUTFILE"
    echo "" >> "$OUTFILE"

    if [[ -f "$MANIFEST_FILE" ]]; then
      endpoint_path=$(jq -r --arg label "$label" --arg type "$type" 'select(.label==$label and .type==$type) | .path' "$MANIFEST_FILE" 2>/dev/null | head -1 || true)
      endpoint_method=$(jq -r --arg label "$label" --arg type "$type" 'select(.label==$label and .type==$type) | .method' "$MANIFEST_FILE" 2>/dev/null | head -1 || true)
      if [[ -n "$endpoint_path" && -n "$endpoint_method" ]]; then
        echo "**Endpoint:** \`${endpoint_method} ${endpoint_path}\`" >> "$OUTFILE"
        echo "" >> "$OUTFILE"
      fi
    fi

    if [[ -s "$requestfile" ]]; then
      echo "**Request JSON:**" >> "$OUTFILE"
      echo '```json' >> "$OUTFILE"
      cat "$requestfile" >> "$OUTFILE"
      echo '' >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      echo "" >> "$OUTFILE"
    fi

    if [[ "$http_code" != "200" ]]; then
      echo "> **Probe failed:** HTTP ${http_code}" >> "$OUTFILE"
      echo "" >> "$OUTFILE"
      continue
    fi

    # Check if valid JSON
    if ! jq empty "$jsonfile" 2>/dev/null; then
      echo "> **Probe returned non-JSON response**" >> "$OUTFILE"
      echo "" >> "$OUTFILE"
      continue
    fi

    filesize=$(wc -c < "$jsonfile")

    if [[ "$type" == "schema" ]]; then
      # Extract the first top-level key that contains the entity object
      # (e.g. "rule", "alias", "server", "client", "host", etc.)
      top_key=$(jq -r 'keys[0] // empty' "$jsonfile" 2>/dev/null || true)

      if [[ -n "$top_key" ]]; then
        echo "**Payload key:** \`${top_key}\`" >> "$OUTFILE"
        echo "" >> "$OUTFILE"

        # Extract fields from the entity object
        field_count=$(jq -r ".\"${top_key}\" | keys | length" "$jsonfile" 2>/dev/null || echo "0")

        if [[ "$field_count" -gt 0 ]]; then
          echo "| Field | Default | Type (inferred) |" >> "$OUTFILE"
          echo "|-------|---------|-----------------|" >> "$OUTFILE"

          jq -r --arg tk "$top_key" '
            .[$tk] // {} | to_entries[] |
            # Infer type from value shape
            .key as $k |
            (if .value | type == "object" then
              # Check if it looks like an enum dict
              if (.value | to_entries | length > 0) and
                 (.value | to_entries[0].value | type == "object") and
                 (.value | to_entries[0].value | has("value"))
              then
                # Collect selected + all options
                (.value | to_entries | map(
                  if .value.selected == 1 then "*" + .key + "*" else .key end
                ) | join(", ")) as $opts |
                "| `\($k)` | enum | `enum`: \($opts) |"
              else
                (.value | tostring | .[0:60]) as $preview |
                "| `\($k)` | (object) | `object`: \($preview) |"
              end
            elif .value | type == "array" then
              "| `\($k)` | [] | `list` |"
            elif .value | type == "string" then
              if .value == "0" or .value == "1" then
                "| `\($k)` | `\"\(.value)\"` | `string-bool` |"
              elif (.value | test("^[0-9]+$")) then
                "| `\($k)` | `\"\(.value)\"` | `int-like string` |"
              else
                (.value | .[0:50]) as $v |
                "| `\($k)` | `\"\($v)\"` | `string` |"
              end
            elif .value | type == "number" then
              "| `\($k)` | `\(.value)` | `number` |"
            elif .value | type == "null" then
              "| `\($k)` | `null` | `nullable` |"
            else
              "| `\($k)` | `\(.value)` | `\(.value | type)` |"
            end)
          ' "$jsonfile" >> "$OUTFILE" 2>/dev/null || echo "| (parse error) | — | — |" >> "$OUTFILE"

          echo "" >> "$OUTFILE"
          echo "> ${field_count} fields discovered" >> "$OUTFILE"
        else
          echo "> Empty schema or unknown structure (${filesize} bytes)" >> "$OUTFILE"
        fi
      else
        echo "> Empty response or unknown structure (${filesize} bytes)" >> "$OUTFILE"
      fi

    elif [[ "$type" == "search" ]]; then
      # Show row count and first row keys
      row_count=$(jq -r '.rows | length // 0' "$jsonfile" 2>/dev/null || echo "0")
      total=$(jq -r '.total // .rowCount // "?"' "$jsonfile" 2>/dev/null || echo "?")

      echo "**Rows returned:** ${row_count} (total: ${total})" >> "$OUTFILE"
      echo "" >> "$OUTFILE"

      if [[ "$row_count" -gt 0 ]]; then
        echo "**Row keys:**" >> "$OUTFILE"
        echo '```' >> "$OUTFILE"
        jq -r '.rows[0] | keys[]' "$jsonfile" 2>/dev/null >> "$OUTFILE" || echo "(parse error)" >> "$OUTFILE"
        echo '```' >> "$OUTFILE"
        echo "" >> "$OUTFILE"
        echo "**First row sample:**" >> "$OUTFILE"
        echo '```json' >> "$OUTFILE"
        jq -C '.rows[0]' "$jsonfile" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' >> "$OUTFILE" || echo "(parse error)" >> "$OUTFILE"
        echo '```' >> "$OUTFILE"
      fi

    elif [[ "$type" == "global" ]]; then
      # Show top-level keys and structure summary
      echo "**Top-level keys:**" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      jq -r 'keys[]' "$jsonfile" 2>/dev/null | head -30 >> "$OUTFILE" || echo "(parse error)" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      echo "" >> "$OUTFILE"
      echo "**Response sample:**" >> "$OUTFILE"
      echo '```json' >> "$OUTFILE"
      jq -C '.' "$jsonfile" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' | head -80 >> "$OUTFILE" || echo "(parse error)" >> "$OUTFILE"
      echo '```' >> "$OUTFILE"
      echo "" >> "$OUTFILE"
      echo "> Response size: ${filesize} bytes" >> "$OUTFILE"
    fi

    echo "" >> "$OUTFILE"
  done

  echo "---" >> "$OUTFILE"
  echo "" >> "$OUTFILE"
done

# ---------------------------------------------------------------------------
# Footer — Probe summary
# ---------------------------------------------------------------------------
echo "## Probe Summary" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "| Status | Count |" >> "$OUTFILE"
echo "|--------|-------|" >> "$OUTFILE"

ok_count=$(find "$INDIR" -name "*.http" -exec grep -l "^200$" {} \; 2>/dev/null | wc -l)
fail_count=$(find "$INDIR" -name "*.http" ! -exec grep -q "^200$" {} \; -print 2>/dev/null | wc -l)
total_count=$(find "$INDIR" -name "*.http" 2>/dev/null | wc -l)

echo "| OK (200) | ${ok_count} |" >> "$OUTFILE"
echo "| Failed | ${fail_count} |" >> "$OUTFILE"
echo "| Total | ${total_count} |" >> "$OUTFILE"
echo "" >> "$OUTFILE"

# List failures
if [[ "$fail_count" -gt 0 ]]; then
  echo "### Failed Endpoints" >> "$OUTFILE"
  echo "" >> "$OUTFILE"
  echo "| Endpoint | HTTP |" >> "$OUTFILE"
  echo "|----------|------|" >> "$OUTFILE"

  for httpfile in "$INDIR"/*.http; do
    code=$(<"$httpfile")
    if [[ "$code" != "200" ]]; then
      base=$(basename "$httpfile" .http)
      echo "| \`${base}\` | ${code} |" >> "$OUTFILE"
    fi
  done
  echo "" >> "$OUTFILE"
fi

echo "---" >> "$OUTFILE"
echo "" >> "$OUTFILE"
echo "> Generated: ${TIMESTAMP} | OPNsense \`${OPN_VERSION}\`" >> "$OUTFILE"
echo "> Script: \`tools/opnsense/scripts/build-api-schema-audit.sh\`" >> "$OUTFILE"

echo "Audit written: $OUTFILE ($(wc -l < "$OUTFILE") lines)"
